In [1]:
"""
1. 这里主要是读取一下拼接的数据，然后查看表头列，后续拼接Label标签
"""

'\n1. 这里主要是读取一下拼接的数据，然后查看表头列，后续拼接Label标签\n'

In [2]:
import pandas as pd
import numpy as np

In [5]:
df1 = pd.read_csv('/Users/liuchang/PycharmProjects/New_EKG_CreditRating/DataProcessing/output_data/basic_financial_info.csv',index_col=0)

In [6]:
df1.head(5)

,ListedCoID,SecurityID,Symbol,ShortName,EndDate,IndustryName,IndustryCode,RegisterAddress,OfficeAddress,SocialCreditCode,...,F070201B,F070301B,F040202B,F040502B,F041702B,F080101A,F080301A,F080601A,F081202B,F081602C
0,101704,201000003384,1,平安银行,2018-12-31,货币金融服务,J66,广东省深圳市罗湖区深南东路5047号,广东省深圳市深南东路5047号,91440300192185379H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,101775,201000003384,2,万科A,2018-12-31,房地产业,K70,广东省深圳市盐田区大梅沙环梅路33号万科中心,广东省深圳市盐田区大梅沙环梅路33号万科中心,91440300192181490G,...,1.0,1.382016,NaN,NaN,0.002929,1.189227,0.189227,0.189642,-0.083400,218.782276
2,102294,201000000004,4,国农科技,2018-12-31,医药制造业,C27,广东省深圳市南山区中心路(深圳湾段)3333号中铁南方总部大厦503室,广东省深圳市南山区中心路(深圳湾段)3333号中铁南方总部大厦503室,91440300192441969E,...,1.0,0.854843,9.175674,NaN,0.004185,1.126233,0.126233,0.016430,43.519092,0.049999
3,102295,201000000005,5,世纪星源,2018-12-31,生态保护和环境治理业,N77,广东省深圳市罗湖区深南东路2017号华乐大厦3楼,广东省深圳市罗湖区深南东路2017号华乐大厦3楼,914403006188470942,...,1.0,3.754066,85.032064,2.101236,0.042320,1.089658,0.089658,0.021008,15.112391,11.786389
4,102296,201000000006,6,深振业A,2018-12-31,房地产业,K70,广东省深圳市罗湖区桂园街道宝安南路2014号振业大厦A座31层,广东省深圳市南山区科技南路16号深圳湾科技生态园11栋A座42-43层,91440300618831041G,...,1.0,1.364668,11.698421,1.220429,0.013116,1.032333,0.032333,0.039896,0.650917,-0.268711

In [7]:
df1.columns

Index(['ListedCoID', 'SecurityID', 'Symbol', 'ShortName', 'EndDate',
       'IndustryName', 'IndustryCode', 'RegisterAddress', 'OfficeAddress',
       'SocialCreditCode', 'Sigchange', 'FullName', 'LegalRepresentative',
       'EstablishDate', 'RegisterCapital', 'Website', 'BusinessScope',
       'F010101A', 'F010201A', 'F010401A', 'F010702B', 'F011201A', 'F011301A',
       'F030801A', 'F030901A', 'F031201A', 'F050202B', 'F051101B', 'F051201B',
       'F051401B', 'F051501B', 'F052401B', 'F070101B', 'F070201B', 'F070301B',
       'F040202B', 'F040502B', 'F041702B', 'F080101A', 'F080301A', 'F080601A',
       'F081202B', 'F081602C'],
      dtype='object')